
package org.example.ClientWS;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "ReleveService", targetNamespace = "http://Web_Service.example.org/", wsdlLocation = "http://localhost:9191/?wsdl")
public class ReleveService
    extends Service
{

    private final static URL RELEVESERVICE_WSDL_LOCATION;
    private final static WebServiceException RELEVESERVICE_EXCEPTION;
    private final static QName RELEVESERVICE_QNAME = new QName("http://Web_Service.example.org/", "ReleveService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9191/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RELEVESERVICE_WSDL_LOCATION = url;
        RELEVESERVICE_EXCEPTION = e;
    }

    public ReleveService() {
        super(__getWsdlLocation(), RELEVESERVICE_QNAME);
    }

    public ReleveService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RELEVESERVICE_QNAME, features);
    }

    public ReleveService(URL wsdlLocation) {
        super(wsdlLocation, RELEVESERVICE_QNAME);
    }

    public ReleveService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RELEVESERVICE_QNAME, features);
    }

    public ReleveService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReleveService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Releve
     */
    @WebEndpoint(name = "RelevePort")
    public Releve getRelevePort() {
        return super.getPort(new QName("http://Web_Service.example.org/", "RelevePort"), Releve.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Releve
     */
    @WebEndpoint(name = "RelevePort")
    public Releve getRelevePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Web_Service.example.org/", "RelevePort"), Releve.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RELEVESERVICE_EXCEPTION!= null) {
            throw RELEVESERVICE_EXCEPTION;
        }
        return RELEVESERVICE_WSDL_LOCATION;
    }

}
