
package org.example.ClientWS;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Releve", targetNamespace = "http://Web_Service.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Releve {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "toString", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.ToString")
    @ResponseWrapper(localName = "toStringResponse", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.ToStringResponse")
    @Action(input = "http://Web_Service.example.org/Releve/toStringRequest", output = "http://Web_Service.example.org/Releve/toStringResponse")
    public String toString();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "ajout", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.Ajout")
    @ResponseWrapper(localName = "ajoutResponse", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.AjoutResponse")
    @Action(input = "http://Web_Service.example.org/Releve/ajoutRequest", output = "http://Web_Service.example.org/Releve/ajoutResponse")
    public void ajout(
        @WebParam(name = "arg0", targetNamespace = "")
        Operation arg0);

    /**
     * 
     */
    @WebMethod(operationName = "ListOperation")
    @RequestWrapper(localName = "ListOperation", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.ListOperation")
    @ResponseWrapper(localName = "ListOperationResponse", targetNamespace = "http://Web_Service.example.org/", className = "org.example.ClientWS.ListOperationResponse")
    @Action(input = "http://Web_Service.example.org/Releve/ListOperationRequest", output = "http://Web_Service.example.org/Releve/ListOperationResponse")
    public void listOperation();

}
